version: '3'
services:
  api:
    build: ./api
    container_name: 'GM2-API-UBUNTU'
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: "/root/.rbenv/shims/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
      - mysql-data:/var/lib/mysql
    
  view:
    build: ./view
    command: npm run serve
    container_name: 'GM2-VIEW'
    ports:
      - "8080:8080"
    volumes:
      - ./view:/app
      - code_share:/app/vue-project/dist
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000
    depends_on:
      - api

  admin_view:
    build: ./admin_view
    container_name: 'GM2-ADMIN-VIEW'
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - ./admin_view:/app
    tty: true
    environment:
      - VUE_APP_URL=http://localhost:3000

volumes:
  mysql-data:
    driver: local
  code_share: 
